Admin.Web.UI/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Web.UI.Controllers
{
    public class PartialController : Controller
    {
        public PartialViewResult DrawerPartial()
        {
            var data = new List<string>();
            return PartialView("Partial/_DrawerPartial", data);
        }

        public PartialViewResult HeaderPartial()
        {
            return PartialView("Partial/_HeaderPartial");
        }

        public PartialViewResult ModalPartial()
        {
            return PartialView("Partial/_ModalPartial");
        }
    }
}

Admin.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Admin.Web.UI/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html class="app-ui" lang="tr">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>@ViewBag.Title - WissenAkademie ASP.Net MVC</title>

    <meta name="description" content="ASP.Net MVC ile template giydirme eğitimi" />
    <meta name="author" content="Mesut" />
    <meta name="robots" content="noindex, nofollow" />
    <link rel="apple-touch-icon" href="~/assets/img/favicons/apple-touch-icon.png" />
    <link rel="icon" href="~/assets/img/favicons/favicon.ico" />

    <!-- Google fonts -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,900%7CRoboto+Slab:300,400%7CRoboto+Mono:400" />



    <!-- AppUI CSS stylesheets -->
    @Styles.Render("~/bundle/css")
    @RenderSection("top", false)
</head>
<body class="app-ui layout-has-drawer layout-has-fixed-header">
    <div class="app-layout-canvas">
        <div class="app-layout-container">
            <!-- Drawer -->
            @{Html.RenderAction("DrawerPartial", "Partial");}
            <!-- End drawer -->
            <!-- Header -->
            @{Html.RenderAction("HeaderPartial", "Partial");}
            <!-- End header -->
            <main class="app-layout-content">
                <!-- Page Content -->
                <div class="container-fluid p-y-md">
                    @RenderBody()
                </div>
                <!-- End Page Content -->
            </main>
        </div>
        <!-- .app-layout-container -->
    </div>
    <!-- .app-layout-canvas -->
    <!-- Apps Modal -->
    <!-- Opens from the button in the header -->
    @{Html.RenderAction("ModalPartial", "Partial");}
    <!-- End Apps Modal -->
    <div class="app-ui-mask-modal"></div>
    <!-- AppUI Core JS: jQuery, Bootstrap, slimScroll, scrollLock and App.js -->
    @Scripts.Render("~/bundle/js")

    @RenderSection("bottom", false)
</body>
</html>